// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Struktur data Item
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`                         // Barcode unik barang
	NamaBarang    string                 `protobuf:"bytes,2,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"` // Nama barang
	QtyOnhand     int32                  `protobuf:"varint,3,opt,name=qty_onhand,json=qtyOnhand,proto3" json:"qty_onhand,omitempty"`   // Jumlah stok tersedia
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Item) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *Item) GetQtyOnhand() int32 {
	if x != nil {
		return x.QtyOnhand
	}
	return 0
}

// Request untuk menambah item baru
type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	NamaBarang    string                 `protobuf:"bytes,2,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	QtyOnhand     int32                  `protobuf:"varint,3,opt,name=qty_onhand,json=qtyOnhand,proto3" json:"qty_onhand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *AddItemRequest) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *AddItemRequest) GetQtyOnhand() int32 {
	if x != nil {
		return x.QtyOnhand
	}
	return 0
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *AddItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request untuk scan barcode
type ScanBarcodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanBarcodeRequest) Reset() {
	*x = ScanBarcodeRequest{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanBarcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanBarcodeRequest) ProtoMessage() {}

func (x *ScanBarcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanBarcodeRequest.ProtoReflect.Descriptor instead.
func (*ScanBarcodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ScanBarcodeRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

// Request untuk update stok (barang masuk/keluar)
type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`    // Positif = masuk, Negatif = keluar
	Keterangan    string                 `protobuf:"bytes,3,opt,name=keterangan,proto3" json:"keterangan,omitempty"` // "Pembelian", "Penjualan", "Return", dll
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateStockRequest) GetKeterangan() string {
	if x != nil {
		return x.Keterangan
	}
	return ""
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StokSebelum   int32                  `protobuf:"varint,3,opt,name=stok_sebelum,json=stokSebelum,proto3" json:"stok_sebelum,omitempty"`
	StokSesudah   int32                  `protobuf:"varint,4,opt,name=stok_sesudah,json=stokSesudah,proto3" json:"stok_sesudah,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStockResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateStockResponse) GetStokSebelum() int32 {
	if x != nil {
		return x.StokSebelum
	}
	return 0
}

func (x *UpdateStockResponse) GetStokSesudah() int32 {
	if x != nil {
		return x.StokSesudah
	}
	return 0
}

// Request untuk list semua item
type ListItemsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OnlyLowStock      bool                   `protobuf:"varint,1,opt,name=only_low_stock,json=onlyLowStock,proto3" json:"only_low_stock,omitempty"` // Filter item dengan stok rendah
	LowStockThreshold int32                  `protobuf:"varint,2,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListItemsRequest) GetOnlyLowStock() bool {
	if x != nil {
		return x.OnlyLowStock
	}
	return false
}

func (x *ListItemsRequest) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request untuk cek stok
type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CheckStockRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type CheckStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	NamaBarang    string                 `protobuf:"bytes,2,opt,name=nama_barang,json=namaBarang,proto3" json:"nama_barang,omitempty"`
	QtyOnhand     int32                  `protobuf:"varint,3,opt,name=qty_onhand,json=qtyOnhand,proto3" json:"qty_onhand,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "Tersedia", "Stok Rendah", "Habis"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *CheckStockResponse) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CheckStockResponse) GetNamaBarang() string {
	if x != nil {
		return x.NamaBarang
	}
	return ""
}

func (x *CheckStockResponse) GetQtyOnhand() int32 {
	if x != nil {
		return x.QtyOnhand
	}
	return 0
}

func (x *CheckStockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\tinventory\"`\n" +
	"\x04Item\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x1f\n" +
	"\vnama_barang\x18\x02 \x01(\tR\n" +
	"namaBarang\x12\x1d\n" +
	"\n" +
	"qty_onhand\x18\x03 \x01(\x05R\tqtyOnhand\"j\n" +
	"\x0eAddItemRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x1f\n" +
	"\vnama_barang\x18\x02 \x01(\tR\n" +
	"namaBarang\x12\x1d\n" +
	"\n" +
	"qty_onhand\x18\x03 \x01(\x05R\tqtyOnhand\"P\n" +
	"\x0fAddItemResponse\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.inventory.ItemR\x04item\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x12ScanBarcodeRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"j\n" +
	"\x12UpdateStockRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1e\n" +
	"\n" +
	"keterangan\x18\x03 \x01(\tR\n" +
	"keterangan\"\x9a\x01\n" +
	"\x13UpdateStockResponse\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.inventory.ItemR\x04item\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fstok_sebelum\x18\x03 \x01(\x05R\vstokSebelum\x12!\n" +
	"\fstok_sesudah\x18\x04 \x01(\x05R\vstokSesudah\"h\n" +
	"\x10ListItemsRequest\x12$\n" +
	"\x0eonly_low_stock\x18\x01 \x01(\bR\fonlyLowStock\x12.\n" +
	"\x13low_stock_threshold\x18\x02 \x01(\x05R\x11lowStockThreshold\"P\n" +
	"\x11ListItemsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.inventory.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x11CheckStockRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"\x86\x01\n" +
	"\x12CheckStockResponse\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x1f\n" +
	"\vnama_barang\x18\x02 \x01(\tR\n" +
	"namaBarang\x12\x1d\n" +
	"\n" +
	"qty_onhand\x18\x03 \x01(\x05R\tqtyOnhand\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xf4\x02\n" +
	"\x10InventoryService\x12@\n" +
	"\aAddItem\x12\x19.inventory.AddItemRequest\x1a\x1a.inventory.AddItemResponse\x12=\n" +
	"\vScanBarcode\x12\x1d.inventory.ScanBarcodeRequest\x1a\x0f.inventory.Item\x12L\n" +
	"\vUpdateStock\x12\x1d.inventory.UpdateStockRequest\x1a\x1e.inventory.UpdateStockResponse\x12I\n" +
	"\n" +
	"CheckStock\x12\x1c.inventory.CheckStockRequest\x1a\x1d.inventory.CheckStockResponse\x12F\n" +
	"\tListItems\x12\x1b.inventory.ListItemsRequest\x1a\x1c.inventory.ListItemsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_inventory_proto_goTypes = []any{
	(*Item)(nil),                // 0: inventory.Item
	(*AddItemRequest)(nil),      // 1: inventory.AddItemRequest
	(*AddItemResponse)(nil),     // 2: inventory.AddItemResponse
	(*ScanBarcodeRequest)(nil),  // 3: inventory.ScanBarcodeRequest
	(*UpdateStockRequest)(nil),  // 4: inventory.UpdateStockRequest
	(*UpdateStockResponse)(nil), // 5: inventory.UpdateStockResponse
	(*ListItemsRequest)(nil),    // 6: inventory.ListItemsRequest
	(*ListItemsResponse)(nil),   // 7: inventory.ListItemsResponse
	(*CheckStockRequest)(nil),   // 8: inventory.CheckStockRequest
	(*CheckStockResponse)(nil),  // 9: inventory.CheckStockResponse
}
var file_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.AddItemResponse.item:type_name -> inventory.Item
	0, // 1: inventory.UpdateStockResponse.item:type_name -> inventory.Item
	0, // 2: inventory.ListItemsResponse.items:type_name -> inventory.Item
	1, // 3: inventory.InventoryService.AddItem:input_type -> inventory.AddItemRequest
	3, // 4: inventory.InventoryService.ScanBarcode:input_type -> inventory.ScanBarcodeRequest
	4, // 5: inventory.InventoryService.UpdateStock:input_type -> inventory.UpdateStockRequest
	8, // 6: inventory.InventoryService.CheckStock:input_type -> inventory.CheckStockRequest
	6, // 7: inventory.InventoryService.ListItems:input_type -> inventory.ListItemsRequest
	2, // 8: inventory.InventoryService.AddItem:output_type -> inventory.AddItemResponse
	0, // 9: inventory.InventoryService.ScanBarcode:output_type -> inventory.Item
	5, // 10: inventory.InventoryService.UpdateStock:output_type -> inventory.UpdateStockResponse
	9, // 11: inventory.InventoryService.CheckStock:output_type -> inventory.CheckStockResponse
	7, // 12: inventory.InventoryService.ListItems:output_type -> inventory.ListItemsResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
